on:
  push:
    branches:
      - az-ps-login
jobs:
  build_test_job:
    name: 'Build and test job'
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
    steps:

    - name: 'Checking out repo code'
      uses: actions/checkout@v2

    - name: 'Validate build'
      run: |
        pwd
        ls -lrt
        npm install
        npm run-script build
        
    - name: 'Run L0 tests'
      run: |
        npm test
