on:
  push:
    branches:
      - az-ps-login
jobs:
  build_test_job:
    name: 'Build and test job'
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]
    steps:

    - name: 'Checking out repo code'
      uses: actions/checkout@v2

    - name: 'Validate build'
      run: |
        cd ${{github.workspace}}/login
        npm install
        npm run build
        
    - name: 'Run L0 tests'
      run: |
        cd ${{github.workspace}}/login
        npm run test
