on:
  push:
    branches:
      - test-branch

jobs:
  build_test_job:
    name: 'Build and test job'
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]
    steps:

    - name: 'Running az login releases v1'
      uses: Azure/login@releases/v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
